defmodule Autoforge.Repo.Migrations.RefactorGlobalProviderKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:llm_provider_keys, [:user_id, :provider],
                     name: "llm_provider_keys_unique_provider_per_user_index"
                   )

    create unique_index(:llm_provider_keys, [:name], name: "llm_provider_keys_unique_name_index")

    # Add column as nullable first so we can backfill existing bots
    alter table(:bots) do
      add :llm_provider_key_id,
          references(:llm_provider_keys,
            column: :id,
            name: "bots_llm_provider_key_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # Backfill: match each bot to a provider key by extracting the provider
    # from the model string (provider:model_id format) and matching by user_id
    execute """
    UPDATE bots
    SET llm_provider_key_id = (
      SELECT k.id FROM llm_provider_keys k
      WHERE k.user_id = bots.user_id
        AND k.provider = split_part(bots.model, ':', 1)
      LIMIT 1
    )
    WHERE llm_provider_key_id IS NULL
    """

    # Now make the column NOT NULL
    alter table(:bots) do
      modify :llm_provider_key_id, :uuid, null: false
    end

    # Drop user_id from llm_provider_keys after backfill is done
    alter table(:llm_provider_keys) do
      remove :user_id
    end
  end

  def down do
    alter table(:llm_provider_keys) do
      add :user_id,
          references(:users,
            column: :id,
            name: "llm_provider_keys_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:llm_provider_keys, [:user_id, :provider],
             name: "llm_provider_keys_unique_provider_per_user_index"
           )

    drop_if_exists unique_index(:llm_provider_keys, [:name],
                     name: "llm_provider_keys_unique_name_index"
                   )

    drop constraint(:bots, "bots_llm_provider_key_id_fkey")

    alter table(:bots) do
      remove :llm_provider_key_id
    end
  end
end
