defmodule Autoforge.Repo.Migrations.AddConnecteamApiKeyConfigs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:connecteam_api_key_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :region, :text, null: false, default: "global"
      add :enabled, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_api_key, :binary, null: false
    end
  end

  def down do
    drop table(:connecteam_api_key_configs)
  end
end
