defmodule Autoforge.Repo.Migrations.AddStartupScriptToTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_templates) do
      add :startup_script, :text
    end
  end

  def down do
    alter table(:project_templates) do
      remove :startup_script
    end
  end
end
