defmodule Autoforge.Repo.Migrations.AddDockerfileTemplateToProjectTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:project_templates) do
      add :dockerfile_template, :text
    end
  end

  def down do
    alter table(:project_templates) do
      remove :dockerfile_template
    end
  end
end
