defmodule Autoforge.Repo.Migrations.AddBots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :system_prompt, :text
      add :model, :text, null: false
      add :temperature, :decimal, default: "0.7"
      add :max_tokens, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "bots_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:bots, [:user_id, :name], name: "bots_unique_name_per_user_index")
  end

  def down do
    drop_if_exists unique_index(:bots, [:user_id, :name], name: "bots_unique_name_per_user_index")

    drop constraint(:bots, "bots_user_id_fkey")

    drop table(:bots)
  end
end
