defmodule Autoforge.Repo.Migrations.AddNetworkAndSubnetworkToVmTemplates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vm_templates) do
      add :network, :text
      add :subnetwork, :text
    end
  end

  def down do
    alter table(:vm_templates) do
      remove :subnetwork
      remove :network
    end
  end
end
